package com.unsa.PhotoSharing.persistence.entity;

// default package
// Generated 08/06/2014 12:26:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comentario generated by hbm2java
 */
@Entity
@Table(name = "comentario", catalog = "photosharing")
public class Comentario implements java.io.Serializable {

	private Integer idComentario;
	private Foto foto;
	private Usuario usuario;
	private String comentario;
	private Date comentDate;

	public Comentario() {
	}

	public Comentario(Foto foto, Usuario usuario) {
		this.foto = foto;
		this.usuario = usuario;
	}

	public Comentario(Foto foto, Usuario usuario, String comentario,
			Date comentDate) {
		this.foto = foto;
		this.usuario = usuario;
		this.comentario = comentario;
		this.comentDate = comentDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idComentario", unique = true, nullable = false)
	public Integer getIdComentario() {
		return this.idComentario;
	}

	public void setIdComentario(Integer idComentario) {
		this.idComentario = idComentario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFoto", nullable = false)
	public Foto getFoto() {
		return this.foto;
	}

	public void setFoto(Foto foto) {
		this.foto = foto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "idUsuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "Comentario", length = 65535)
	public String getComentario() {
		return this.comentario;
	}

	public void setComentario(String comentario) {
		this.comentario = comentario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ComentDate", length = 19)
	public Date getComentDate() {
		return this.comentDate;
	}

	public void setComentDate(Date comentDate) {
		this.comentDate = comentDate;
	}

}
