package com.unsa.PhotoSharing.persistence.entity;

// default package
// Generated 08/06/2014 12:26:52 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LikeId generated by hbm2java
 */
@Embeddable
public class LikeId implements java.io.Serializable {

	private int idUsuario;
	private int idFoto;

	public LikeId() {
	}

	public LikeId(int idUsuario, int idFoto) {
		this.idUsuario = idUsuario;
		this.idFoto = idFoto;
	}

	@Column(name = "idUsuario", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "idFoto", nullable = false)
	public int getIdFoto() {
		return this.idFoto;
	}

	public void setIdFoto(int idFoto) {
		this.idFoto = idFoto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LikeId))
			return false;
		LikeId castOther = (LikeId) other;

		return (this.getIdUsuario() == castOther.getIdUsuario())
				&& (this.getIdFoto() == castOther.getIdFoto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUsuario();
		result = 37 * result + this.getIdFoto();
		return result;
	}

}
