package com.unsa.PhotoSharing.persistence.entity;

// default package
// Generated 08/06/2014 12:26:52 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Like generated by hbm2java
 */
@Entity
@Table(name = "like", catalog = "photosharing")
public class Like implements java.io.Serializable {

	private LikeId id;
	private Foto foto;
	private Usuario usuario;
	private Boolean liked;
	private Date likedDate;

	public Like() {
	}

	public Like(LikeId id, Foto foto, Usuario usuario) {
		this.id = id;
		this.foto = foto;
		this.usuario = usuario;
	}

	public Like(LikeId id, Foto foto, Usuario usuario, Boolean liked,
			Date likedDate) {
		this.id = id;
		this.foto = foto;
		this.usuario = usuario;
		this.liked = liked;
		this.likedDate = likedDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUsuario", column = @Column(name = "idUsuario", nullable = false)),
			@AttributeOverride(name = "idFoto", column = @Column(name = "idFoto", nullable = false)) })
	public LikeId getId() {
		return this.id;
	}

	public void setId(LikeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFoto", nullable = false, insertable = false, updatable = false)
	public Foto getFoto() {
		return this.foto;
	}

	public void setFoto(Foto foto) {
		this.foto = foto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "Liked")
	public Boolean getLiked() {
		return this.liked;
	}

	public void setLiked(Boolean liked) {
		this.liked = liked;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LikedDate", length = 19)
	public Date getLikedDate() {
		return this.likedDate;
	}

	public void setLikedDate(Date likedDate) {
		this.likedDate = likedDate;
	}

}
